name: Testing Discord webhook now

on:
  push:
    branches:
      - e11.18-discord-hook
    # paths:
    #   - 'discord.yml'

jobs:
  discord_webhook_job:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Run a sample step
      run: echo "This is a test step"

    # - name: Github context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: echo "$GITHUB_CONTEXT"

    - name: Build success discord notification
      if: ${{ success() && (contains(join(github.event.commits.*.message, ' '), '#discord') == true) }}
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: PetriA
        COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }} 
        DISCORD_EMBEDS: >
          [{
            "type":"Info",
            "title":"Pokedex build",
            "description":"Successful build from repo: ${{github.event.repository.name}}",
            "color":40811,
            "timestamp":"${{github.event.head_commit.timestamp}}",
            "footer":{"text":"${{github.event.head_commit.timestamp}}"}
          }]
      uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
      with:
        args: "A new version of Pokedex deployed by ${{ github.actor }}."
    - name: Build success discord notification
      if: ${{ failure() }}
      env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: PetriA
          COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }} 
          DISCORD_EMBEDS: >
            [{
              "type": "Error",
              "title": "Pokedex build",
              "description": "Failed build from repo: ${{ github.repository }}",
              "fields":[{
                    {"name":"Commit Message","value":"[${{ github.sha }}](https://github.com/${{github.repository}}/commit/${{github.sha}}) - `${{github.event.head_commit.message}}`"},
                    {"name":"Changed Files","value":"${{ steps.changed-files.outputs.all_changed_files }}"},
                    {"name":"Author","value":"[${{github.event.head_commit.author.name}}](https://github.com/${{github.actor}})"
                }],
              "color": 16711680,
              "url":"https://github.com/${{github.repository}}/commit/${{github.sha}}",
              "timestamp":"${{github.event.head_commit.timestamp}}",
              "footer":{"text":"${{github.event.head_commit.timestamp}}"}
            }]
      uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
      with:
        args: "A new version of Pokedex deployed by ${{ github.actor }}."
  
    - name: Build success discord notification LONG
      if: ${{ contains(join(github.event.commits.*.message, ' '), '#discordlong') == true }}
      env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: PetriA
          #DISCORD_EMBEDS: '[{"author":{"icon_url":"https://avatars.githubusercontent.com/${{ github.actor }}","name":"${{ github.actor }}","url":"https://github.com/${{github.actor}}"},"url":"https://github.com/${{github.repository}}/commit/${{github.sha}}","fields":[{"name":"Repository","value":"[${{github.event.repository.name}}](${{github.event.repository.clone_url}})","inline":true},{"name":"Branch","value":"[${{github.ref_name}}](https://github.com/${{github.repository}}/tree/${{github.ref_name}})","inline":true},{"name":"Event","value":"${{github.event_name}}","inline":true},{"name":"Job","value":"${{github.job}}","inline":true},{"name":"Commit Message","value":"[${{ github.sha }}](https://github.com/${{github.repository}}/commit/${{github.sha}}) - `${{github.event.head_commit.message}}`"},{"name":"Changed Files","value":"${{ steps.changed-files.outputs.all_changed_files }}"},{"name":"Author","value":"[${{github.event.head_commit.author.name}}](https://github.com/${{github.actor}})"}],"color":1127128,"timestamp":"${{github.event.head_commit.timestamp}}","footer":{"text":"${{github.event.head_commit.timestamp}}"}}]'
          DISCORD_EMBEDS: >
            [{
                "author":{
                    "icon_url":"https://avatars.githubusercontent.com/${{ github.actor }}",
                    "name":"${{ github.actor }}",
                    "url":"https://github.com/${{github.actor}}"
                },
                "url":"https://github.com/${{github.repository}}/commit/${{github.sha}}",
                "fields":[{
                    "name":"Repository","value":"[${{github.event.repository.name}}](${{github.event.repository.clone_url}})","inline":true},
                    {"name":"Branch","value":"[${{github.ref_name}}](https://github.com/${{github.repository}}/tree/${{github.ref_name}})","inline":true},
                    {"name":"Event","value":"${{github.event_name}}","inline":true},{"name":"Job","value":"${{github.job}}","inline":true},
                    {"name":"Commit Message","value":"[${{ github.sha }}](https://github.com/${{github.repository}}/commit/${{github.sha}}) - `${{github.event.head_commit.message}}`"},
                    {"name":"Changed Files","value":"${{ steps.changed-files.outputs.all_changed_files }}"},
                    {"name":"Author","value":"[${{github.event.head_commit.author.name}}](https://github.com/${{github.actor}})"
                }],
                "color":1127128,
                "timestamp":"${{github.event.head_commit.timestamp}}",
                "footer":{"text":"${{github.event.head_commit.timestamp}}"}
            }]  
      uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
      with:
        args: "LONG: A new version of Pokedex deployed by ${{ github.actor }}."
