name: Periodic health check for pokedex

on:
    push:   # activates also on push to main branch
      branches:
      - main
    schedule:
    - cron: '00 18 * * *'

jobs:
  healt_check_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping health check endpoint
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-f7o9.onrender.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 10s
          retry-all: false