name: full-stack-open-pokedex-pipeline

env:
  IS_PULL_REQUEST: ${{ github.event_name == 'push' }}
  # HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  # GITHUB_EVENT_PATH: ${{ github.event_path }}
  # COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  is_skip_presen_in_pull_request_combined_messages:
    if: ${{ github.event_name == 'push' }}  # if the event is a pull request, skip this job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      # - name: github context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      # - name: commits
      #   env:
      #     COMMITS: ${{ toJson(github.event.commits) }}
      #   run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: combine commit messages
        env:
          COMBINED_MESSAGES: ${{ join(env.COMMIT_MESSAGES, ' ') }}
        run: echo "$COMBINED_MESSAGES"
      - name: Contains skip
        env:
          SKIP: ${{ contains(env.COMMIT_MESSAGES, '#skip ') }}
        run: echo "$SKIP"
        
      # - name: Check for #skip in commit messages
      #   run: |
      #     combined_messages=$(echo "$COMMIT_MESSAGES" | tr '\n' ' ')
      #     if echo "$combined_messages" | grep -q '#skip'; then
      #       echo "skip=true" >> $GITHUB_ENV
      #     else
      #       echo "skip=false" >> $GITHUB_ENV
      #     fi
      #     echo "$combined_messages"
      # - name: Combine PR messages
      #   id: combine_pr_messages
      #   run: |
      #     messages=$(jq -r '.commits[].message' < "${{ github.event_path }}")
      #     combined_messages=$(echo "$messages" | tr '\n' ' ')
      #     if echo "$combined_messages" | grep -q '#skip'; then
      #       echo "skip=true" >> $GITHUB_ENV
      #     else
      #       echo "skip=false" >> $GITHUB_ENV
      #     fi
      #     echo "$combined_messages"
      #- name: echo_skip
      #  run: echo "$skip"
          
  # simple_deployment_pipeline:
  #   needs: [is_skip_presen_in_pull_request_combined_messages]
  #   timeout-minutes: 60
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - name: Install dependencies 
  #       run: npm install  
  #     - name: Check style
  #       run: npm run eslint
  #     - run: npm run build
  #     - name: Run all tests
  #       run: npm test
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: npx playwright test
  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #           name: playwright-report
  #           path: playwright-report/
  #           retention-days: 30
  #     - if: ${{ github.env.skip == 'true' }}
  #       name: Trigger deployment
  #       run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  # tag_release:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - if: ${{ github.env.skip == 'true' }}
  #       name: Bump version and push tag
  #       uses: anothrNick/github-tag-action@1.70.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #         DRY_RUN: false
