name: Pokedex CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - run: npm run build
      - name: Run all tests
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
      
      - if: ${{ github.event_name == 'push' && (contains(join(github.event.commits.*.message, ' '), '#skip') == false) }}
        name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Build success discord notification
        if: ${{ success() && (contains(join(github.event.commits.*.message, ' '), '#discord') == true) }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: PetriA
          COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }} 
          DISCORD_EMBEDS: >
            [{
              "type":"Info",
              "title":"Pokedex build",
              "description":"Successful build from repo: ${{github.event.repository.name}}",
              "color":40811,
              "timestamp":"${{github.event.head_commit.timestamp}}",
              "footer":{"text":"${{github.event.head_commit.timestamp}}"}
            }]
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "A new version of Pokedex deployed by ${{ github.actor }}."
      
      - name: Build failure discord notification
        if: ${{ failure() }}
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            DISCORD_USERNAME: PetriA
            COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }} 
            DISCORD_EMBEDS: >
              [{
                "type": "Error",
                "title": "Pokedex build",
                "description": "Failed build from repo: ${{ github.repository }}",
                "fields":[{
                      {"name":"Commit Message","value":"[${{ github.sha }}](https://github.com/${{github.repository}}/commit/${{github.sha}}) - `${{github.event.head_commit.message}}`"},
                      {"name":"Changed Files","value":"${{ steps.changed-files.outputs.all_changed_files }}"},
                      {"name":"Author","value":"[${{github.event.head_commit.author.name}}](https://github.com/${{github.actor}})"
                  }],
                "color": 16711680,
                "url":"https://github.com/${{github.repository}}/commit/${{github.sha}}",
                "timestamp":"${{github.event.head_commit.timestamp}}",
                "footer":{"text":"${{github.event.head_commit.timestamp}}"}
              }]
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: "A new version of Pokedex deployed by ${{ github.actor }}."
  
      # - name: Notify successful deployment
      #   Does NOT currently work
      #   uses: rjstone/discord-webhook-notify@v1.0.4

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'push' && (contains(join(github.event.commits.*.message, ' '), '#skip') == false)}}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false

  github_action_status_report:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Get the status of the last action
        run: echo "The status of the last action was ${{ job.simple_deployment_pipeline.outcome }}"
      - name: Set PR status to success
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'CI/CD Pipeline',
              description: 'All tests passed',
              target_url: '${{ github.run_url }}'
            })